### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by jasoncmcg** [trwalker/generator-express-rest-api#1]
Is there a full example somewhere using this structure in _Expressjs_?  (I could only find PHP.)

I have been using the setup of Route-Controllers-Models as seen in [beerlocker](https://github.com/scottksmith95/beerlocker/tree/master/beerlocker-3.2). So, this is very different to me. I really like the structure and some of the ideas I see in it. I just need a full example to really get a feel for the mental process behind this approach.

Thanks!

**Comment by trwalker** [comment]
Hi Jason, the Controller/Service/Repository pattern is a super set of what I see in beerlocker.  The importance of services/repositories is to keep controllers extremely lean and also separate reusable business logic/data access.  Services should always be your "thick" layer with all the business logic required to create your data model.  Repositories are relatively lean and should only be for retrieving data, not applying any business logic.  I like to keep separation between models and view models.  View models represent the final model a controller returns where models (data models) are generic models returned from services that could be consumed by any controller (not specific to what the controller will return).  You don't need to create model classes in JS because you can create JSON on the fly in contrast to C# or Java.

I have a working example in my marvel node application seen here:

https://github.com/trwalker/marvel-node

Sorry for the delayed response.  Let me know if you have any more questions.

-Tim

**Comment by jasoncmcg** [comment]
That's great. Thank you for that sample. I love the controller versioning and configuration file approach.
